name: Run WhatsApp Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  whatsapp-bot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Create tmp folder (optional, for videos)
      - name: Create tmp folder
        run: mkdir -p tmp

      # 5️⃣ Run the bot
      - name: Run WhatsApp Bot
        run: node index.js
