name: Run WhatsApp Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  whatsapp-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Create tmp folder
        run: mkdir -p tmp

      - name: Run WhatsApp Bot
        run: node index.js
